# chaine prefixe du chemin vers les graphes
inputGraphPrefix: "/Users/jfenchong/Documents/these/données/francais/gexf/fr_03_31_"

# ?
nbRoamingBTSmoy: "/Volumes/LILI/donnees/francais/nd_fr_bts/nb_fr_bts_03_31.csv"

# chemin de sortie des captures (préfixe)
capturesPrefix: "./captures/touristflows31-March-2009-num_"


# icone utilise pour la heatmap
heatMapSprite: "./ressources/ppp.png"

# ATTENTION aux espaces !
arrowsPrefix: "./ressources/Arrow31 March 2009 "

# attention.. aux.. espaces..
writeArrowsPrefix: "./Arrow roaming "

# set to true to enable proxy
useProxy: false
proxyHost: p-goodway.rd.francetelecom.fr
proxyPort: 3128


# initial camera position
initialLat: 48.866
initialLon: 2.359

# camera zoom settings
initialZoom: 10
minZoom: 9
maxZoom: 14

# screen resolution
screenWidth: 1200
screenHeight: 900

# fond de carte: si useMBTiles est vrai, alors cela utilise le fichier de fond de cartes
useTiles: true
pathToTiles: "jdbc:sqlite:/Users/jfenchong/Documents/MapBox/export/Idf2.mbtiles"